default:
  # thresholds based on stats and sampling for European langs without German, Basque
  avg_word_length_min: 3.2
  avg_word_length_max: 7.0

  # thresholds based on stats and sampling for European langs
  alphanumeric_char_ratio_min: 0.77
  alphanumeric_char_ratio_max: 0.86

  # thresholds based on stats and sampling for European langs
  control_char_ratio_max: 0.001
  avg_paragraph_length_words_min: 12
  bulletpoint_ratio_max: 0.8
  ellipsis_ratio_max: 0.3
  hashes_word_ratio_max: 0.1
  tabs_word_ratio_max: 0.1
  other_symbol_char_ratio_max: 0.02
  punctuation_char_ratio_min: 0.008
  punctuation_char_ratio_max: 0.08

  dup_paragraphs_ratio_max: 0.25
  dup_paragraphs_char_ratio_max: 0.2

  # thresholds based on mean + 3x stddev over European langs
  dup_5_gram_char_ratio_max: 0.225
  dup_6_gram_char_ratio_max: 0.205
  dup_7_gram_char_ratio_max: 0.190
  dup_8_gram_char_ratio_max: 0.178
  dup_9_gram_char_ratio_max: 0.168
  dup_10_gram_char_ratio_max: 0.160

  # thresholds based on mean + 4x stddev over European langs
  top_2_gram_char_ratio_max: 0.14
  top_3_gram_char_ratio_max: 0.16
  top_4_gram_char_ratio_max: 0.17

ca:

cs:

de:
  # German words are longer on average
  avg_word_length_min: 3.5
  avg_word_length_max: 8.0
  alphanumeric_char_ratio_max: 0.88

en:

es:

fr:

gl:

it:

nl:

pt:

eu:
  # Basque words are longer on average
  avg_word_length_min: 3.6
  avg_word_length_max: 8.0
  alphanumeric_char_ratio_max: 0.88

ar:
  alphanumeric_char_ratio_min: 0.75
  alphanumeric_char_ratio_max: 0.88
  control_char_ratio_max: 0.002

ko:
  avg_word_length_min: 1.0
  avg_word_length_max: 8.0
  alphanumeric_char_ratio_min: 0.67
  alphanumeric_char_ratio_max: 0.82
  control_char_ratio_max: 0.002
  other_symbol_char_ratio_max: 0.03
  punctuation_char_ratio_min: 0.002
  punctuation_char_ratio_max: 0.24

ja:
  avg_word_length_min: 1
  avg_word_length_max: 8
  alphanumeric_char_ratio_min: 0.7
  alphanumeric_char_ratio_max: 0.95
  control_char_ratio_max: 0.002
  other_symbol_char_ratio_max: 0.03
  punctuation_char_ratio_min: 0.002
  punctuation_char_ratio_max: 0.24

zh:
  # zh "words" are generated by segmenter models
  avg_word_length_min: 0
  avg_word_length_max: 10.0
  alphanumeric_char_ratio_min: 0.60
  alphanumeric_char_ratio_max: 0.93
  control_char_ratio_max: 0.002
  ellipsis_ratio_max: 0.38
  other_symbol_char_ratio_max: 0.03
  punctuation_char_ratio_min: 0.002
  punctuation_char_ratio_max: 0.24
  
  dup_5_gram_char_ratio_max: 0.520
  dup_6_gram_char_ratio_max: 0.540
  dup_7_gram_char_ratio_max: 0.512
  dup_8_gram_char_ratio_max: 0.490
  dup_9_gram_char_ratio_max: 0.476
  dup_10_gram_char_ratio_max: 0.462
  
  top_2_gram_char_ratio_max: 0.29
  top_3_gram_char_ratio_max: 0.29
  top_4_gram_char_ratio_max: 0.28
